
sim:
	g++ sssp.cpp UnorderedWorklist.cpp OrderedWorklist.cpp LocalOrderedWorklist.cpp OBIM.cpp Graph.cpp

dij:
	g++ CRS.cpp sssp_dij.cpp

# ----------------------------------------------------------------
.PHONY: clean
clean:
	rm -f  *~  *.o $(BUILD_DIR)/*.o
